name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore RubberSearch.sln

    - name: Build
      run: dotnet build RubberSearch.sln --configuration Release --no-restore
    
    - name: Build tests
      run: dotnet build Tests/UnitTests/UnitTests.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test Tests/UnitTests/UnitTests.csproj --no-build --verbosity normal
